### ISSUE TITLE
Anki 2.1.50 compatibility

### ISSUE THREAD

**Issue by rwmpelstilzchen** [Quip13/Anki-Zoom#18]
Anki Zoom worked fine in 2.1.49, but in 2.1.50 it produces an error message.

**Comment by mobedoor** [comment]
[Here](https://github.com/mobedoor/Anki-Zoom)

**Comment by rwmpelstilzchen** [comment]
Thank! :-)

If I am not mistaken, while it does not show the error message, it still does not work well because of [this](https://forums.ankiweb.net/t/2-1-50-zooming-in-while-reviewing-results-in-an-unusably-huge-deck-list/19283): zooming in on a card affects the deck browser.

**Comment by GrimPixel** [comment]
@rwmpelstilzchen Paste your error message next time.

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨Anki Zoom⁩':
⁨Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/addons.py", line 244, in loadAddons
    __import__(addon.dir_name)
  File "/home/grim/.local/share/Anki2/addons21/538879081/__init__.py", line 169, in <module>
    setup_menu()
  File "/home/grim/.local/share/Anki2/addons21/538879081/__init__.py", line 146, in setup_menu
    mw.addon_view_menu = getMenu(mw, "&View")
  File "/home/grim/.local/share/Anki2/addons21/538879081/toolbar.py", line 12, in getMenu
    menu = a.menu()
AttributeError: 'QAction' object has no attribute 'menu'

**Comment by rwmpelstilzchen** [comment]
@GrimPixel: Yeah, that would be more helpful.

**Comment by CyberPsyLen** [comment]
I find the same. Since updating to Anki Version ⁨2.1.54 (b6a7760c) - using Mac M1 Silicon⁩, this addon throws error below. I didn't realise how much I needed this addon until I didn't have it!

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 11.3
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-27 12:52:28
Add-ons possibly involved: ⁨538879081⁩

Caught exception:
Traceback (most recent call last):
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "/Users/cyberpsylen/Library/Application Support/Anki2/addons21/538879081/__init__.py", line 110, in AnkiWebView_eventFilter_wrapper
NameError: name 'scrl_threshold' is not defined

**Comment by yfjuu6** [comment]
> [Here](https://github.com/mobedoor/Anki-Zoom)
the Add-on version you posted [here,](https://github.com/mobedoor/Anki-Zoom) It is really compatible with V 2.1.50.
I'm on Windows 11, with Anki V 2.1.54 Qt 6 :

- when switching pages will jump back to the default value.
 - Zoom resets after renaming a particular deck.
- Zoom resets when adding each new card.
 - Zoom resets When I click on a deck to study, then go back to the main page, the zoom scale goes back to 100%, although I have set it to 146% in the config page.

Anki version 2.1.54 is my appropriate version because all my favorite Add_ons compatible with It, so I wouldn't like to update it.
Could anyone please fix it to be combatible with V 2.1.54. I really need this Add_on.
